build: to migrate from circleci to github workflows
binary-com/sinbad pull request #130
Opened 2023-10-16 08:03 UTC by yaswanth-deriv

Changes:

Need to remove circleci and replacing with github workflows

## Type of change

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [X] Release

2023-10-19 03:21 UTC, ali-hosseini-deriv commented
As you can see in the PR checks and circleci config we also have a test job for PRs.
you need to implement that one too.

2023-10-23 11:09 UTC, ali-hosseini-deriv commented on .github/workflows/release_staging.yml
> +    - name: Versioning
you've missed this one @yaswanth-deriv

2023-10-23 11:09 UTC, ali-hosseini-deriv requested changes
please fix the EOF issues

2023-10-24 04:26 UTC, niloofar-deriv reviewed
Nit

2023-10-24 04:26 UTC, niloofar-deriv commented on .github/workflows/test.yml
> +    name: Build And Test
```suggestion
    name: Build and Test
```

2023-10-24 04:26 UTC, niloofar-deriv commented on .github/workflows/test.yml
> +    - name: Npm Install
```suggestion
    - name: Install npm packages
```

2023-10-24 04:26 UTC, niloofar-deriv commented on .github/workflows/release_staging.yml
> +    - name: Npm Install
```suggestion
    - name: Install npm packages
```

2023-10-24 04:26 UTC, niloofar-deriv commented on .github/actions/build/action.yml
> +name: build
```suggestion
name: Build
```

2023-10-24 04:26 UTC, niloofar-deriv commented on .github/workflows/release_production.yml
> +    - name: NPM Install
```suggestion
    - name: Install npm packages
```

2023-10-24 04:27 UTC, niloofar-deriv commented
Please ask @prince-deriv to approve your workflow 🙏

2023-10-24 05:40 UTC, niloofar-deriv approved these changes

2023-10-24 06:04 UTC, ali-hosseini-deriv requested changes
as @niloofar-deriv suggested we can setup node_modules caching for these workflows too.
please check other projects like deriv-static-content or deriv-api-docs for the implementation.

2023-10-24 06:04 UTC, ali-hosseini-deriv commented on .github/workflows/test.yml
> +    environment: Development
we dont need any env vars or secrets here. 
so you can remove this.

2023-10-24 06:06 UTC, ali-hosseini-deriv commented
please remove all the environments: Production or Staging or Development.
they values are the same, so having different environments are just over engineering and doesn't add any value.

2023-10-24 06:07 UTC, yaswanth-deriv commented on .github/workflows/test.yml
> +    environment: Development
OKay I will check it

2023-10-26 04:52 UTC, ali-hosseini-deriv approved these changes

2023-10-26 04:55 UTC, habib-deriv approved these changes

2023-10-26 06:35 UTC, ali-hosseini-deriv commented on .github/workflows/test.yml
> +    runs-on: ubuntu_latest
@yaswanth-deriv this has to be `ubuntu-latest` 
please fix it.
```suggestion
    runs-on: ubuntu-latest
```

2023-10-26 06:47 UTC, ali-hosseini-deriv approved these changes

2023-10-26 07:11 UTC, merged